# Uncomment the next line to define a global platform for your project
# platform :ios, '17.6'

target 'MyFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFramework
  pod 'lottie-ios', '~> 4.0'
end
